name: footprint_flutter_example
description: "Demonstrates how to use the Footprint's Flutter SDK"
publish_to: "none"

environment:
  sdk: ">=3.2.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  footprint_flutter: ^2.0.0-beta.3.1
  cupertino_icons: ^1.0.2

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
